# Generated by Django 5.1.5 on 2025-03-11 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0002_productlist_product_kg_productlist_product_quantity'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('UserEmail', models.EmailField(max_length=50)),
                ('UserPassword', models.IntegerField()),
                ('UserFullName', models.CharField(max_length=50)),
                ('DateOfBirth', models.DateField()),
            ],
        ),
    ]
